const String COOWNER = "COOWNER";
const String MECHANIC = "MECHANIC";
const String MECHANIC_MASTER = "MECHANIC MASTER";
const String MECHANIC_ASSISTANT = "MECHANIC ASSISTANT";

const List<String> POSITIONS = [
  COOWNER,
  MECHANIC,
  MECHANIC_MASTER,
  MECHANIC_ASSISTANT
];
